### ISSUE TITLE
Carousel duplication

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#27]
Adding more than 2 posts (not to the carousel) results in an additional carousel added to the lower half of the homepage.

**Comment by Lynngre** [comment]
@AndreasJonsson I need to test this further. It's not happening on the 'test server' so I'll let you know about this one.

**Comment by AndreasJonsson** [comment]
The general structure of the akvo-sites theme is very confusing.   The contents of the file front-page.php is the following:

```php
<?php while (have_posts()) : the_post(); ?>
  <?php //get_template_part('templates/page', 'header'); ?>
  <?php get_template_part('templates/content', 'page-home'); ?>
<?php endwhile; ?>
```

Why is this a loop?  It seems that the consequence is that the contents of the front page will be duplicated.

However, in custom-widgets.php there is this surprising hack:

```php
    if (!isset($GLOBALS['do_not_duplicate'])) $GLOBALS['do_not_duplicate'][] = "";
```

```php
      $qargs = array(
        'post_type' => $type2,
        'posts_per_page' => 1,
        'post__not_in' => $GLOBALS['do_not_duplicate']
      );
```

```php
          $GLOBALS['do_not_duplicate'][] = get_the_ID();  
```

So, some kinds of widgets will not be duplicated...

**Comment by Lynngre** [comment]
Thanks Andreas. Unfortunately the code is quite messy from what we've found. Currently this duplication is only happening when 'posts' are created (top left in the admin menu). I thought it may be related to which category you select for the post but even those without a category are creating duplicates.

Any idea of how we could improve this?

**Comment by AndreasJonsson** [comment]
Now, I'm not an expert on Wordpress, but the function call 'the_post()' have the side effect of fetching the next post of the current page's list of posts and installing it as the current one in the environment known as "The Loop" in the Wordpress community.  Now, I don't believe that this post is at all going to be referenced, because it doesn't seem like the theme is at all rendering "The Loop" at the front page (which I'm guessing is non-standard behaviour in Wordpress).  Instead, it renders columns of sidebar widgets, where the "single_post" widget fetches a particular post of the page's post list.

This is what I'm guessing at the moment: If you don't have widgets that accounts for all posts in the page's post list, the loop will run until the list is emptied, effectively duplicating (or more) the rendering of any widget that isn't a post of a recognized type (i.e., the duplication isn't blocked by the 'do_not_duplicate' hack.).

So, the fix might be as simple as removing "The Loop" in front-page.php, just leaving:

```php
<?php
get_template_part('templates/content', 'page-home');
```

Also, then the 'do_not_duplicate' hack should be possible to remove.  But it is hard to see if there going to be any other consequences of this.

**Comment by AndreasJonsson** [comment]
I'm changing the 'do_not_duplicate' hack into a slightly less ugly one.  What  the developer was trying to achieve, I believe, is a counter in order to get the next post in each query.  (The database will be queried for each post, which is inefficient.)

The main loop on the front page isn't used as far as I can see so I'm removing it, which should take care of duplication of widgets.
