### ISSUE TITLE
RSR project updates - order

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#386]
@samvthom16 could you check https://footballforwater.org/country/kenya/

apparently the project updates pulled using the API are not appearing in chronological order for this page.

**Comment by samvthom16** [comment]
The updates are being pulled from the API URL https://rsr.akvo.org/rest/v1/project_update/?filter={%27project__partners__in%27:[1060]}&project__primary_location__country__iso_code=ke&format=json&image_thumb_name=big

The updates were being pulled chronologically but were not being displayed properly because each column had two updates being show. Once a different row was added in the page builder to show the second row of updates, the chronological issue was solved.
